# Generated by Django 2.1.4 on 2018-12-07 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('update', models.DateField(auto_now=True)),
                ('videofile', models.FileField(upload_to='')),
            ],
        ),
    ]
